### ISSUE TITLE
bug: supabase build problem

### ISSUE THREAD

**Issue by lucasgonze** [e2b-dev/e2b#13]
**Describe the bug**

Installing 
[    ] info  - Generating static pages (0/4)Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!

**To Reproduce**

```
git clone git@github.com:e2b-dev/e2b.git
cd e2b/
nvm use 16
yarn build
warn  - You have enabled experimental feature (swcPlugins) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[    ] info  - Generating static pages (0/4)Error: either NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY env variables or supabaseUrl and supabaseKey are required!
    at createBrowserSupabaseClient (/home/ubuntu/repo/e2b/node_modules/@supabase/auth-helpers-nextjs/dist/index.js:306:11)
    at /home/ubuntu/repo/e2b/.next/server/pages/_app.js:197:115
    at Ic (/home/ubuntu/repo/e2b/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:59:265)
    at Object.useState (/home/ubuntu/repo/e2b/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:62:268)
    at exports.useState (/home/ubuntu/repo/e2b/node_modules/react/cjs/react.production.min.js:25:394)
    at App (/home/ubuntu/repo/e2b/.next/server/pages/_app.js:197:58)
    at Wc (/home/ubuntu/repo/e2b/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/home/ubuntu/repo/e2b/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/home/ubuntu/repo/e2b/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/home/ubuntu/repo/e2b/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)

```

**Expected behavior**

A build

**Screenshots**
<img width="922" alt="image" src="https://user-images.githubusercontent.com/111581/230451420-3a8cf63b-776b-4f76-87e9-e6eb44145c8e.png">

**Desktop (please complete the following information):**

Environment: 

 - OS: Ubuntu shell in Canonical Multipass in OS X Ventura 13.2, M1 chip

**Comment by mlejva** [comment]
Hi @lucasgonze, from the logs it looks like you didn't set the following environment variables in the `.env` file

```
NEXT_PUBLIC_SUPABASE_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY
```

Did you set them?

**Comment by ValentaTomas** [comment]
Also if you want to just run the app you don't need the `yarn build` command - https://github.com/e2b-dev/e2b#get-started.

If you really want to build it, the env vars mentioned https://github.com/e2b-dev/e2b#3-add-env-vars are still required.

**Comment by lucasgonze** [comment]
Valenta, thanks for your help. I am building because yarn install produces these errors:

```
➤ YN0000: ┌ Link step
➤ YN0007: │ supabase@npm:1.48.1 must be built because it never has been before or the last one failed
➤ YN0007: │ @prisma/engines@npm:4.11.0 must be built because it never has been before or the last one failed
➤ YN0007: │ bufferutil@npm:4.0.7 must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.62 must be built because it never has been before or the last one failed
➤ YN0007: │ utf-8-validate@npm:5.0.10 must be built because it never has been before or the last one failed
➤ YN0009: │ utf-8-validate@npm:5.0.10 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-f30805ae/build.log)
➤ YN0009: │ bufferutil@npm:4.0.7 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-b23a597d/build.log)
➤ YN0007: │ prisma@npm:4.11.0 must be built because it never has been before or the last one failed
➤ YN0007: │ @prisma/client@npm:4.11.0 [556c3] must be built because it never has been before or the last one failed
➤ YN0007: │ ai-api@workspace:. must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 15s 565ms
➤ YN0000: Failed with errors in 16s 233ms
```

**Comment by mlejva** [comment]
Lucas, please follow the get started guide from our readme. You have to call `yarn install:all`

**Comment by lucasgonze** [comment]
install:all produces the same results as a plain `install`:

```
➤ YN0000: ┌ Link step
➤ YN0007: │ bufferutil@npm:4.0.7 must be built because it never has been before or the last one failed
➤ YN0007: │ utf-8-validate@npm:5.0.10 must be built because it never has been before or the last one failed
➤ YN0009: │ bufferutil@npm:4.0.7 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-19592493/build.log)
➤ YN0009: │ utf-8-validate@npm:5.0.10 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-78399284/build.log)
➤ YN0008: │ ai-api@workspace:. must be rebuilt because its dependency tree changed

```

**Comment by mlejva** [comment]
Can you please provide the full terminal output?

**Comment by mlejva** [comment]
Ah, I think this is because you're running on M1

**Comment by mlejva** [comment]
We did some quick research and the problem seems to be this particular library https://github.com/eerohele/sublime-lxml/issues/11

We haven't had time to address it yet though.

**Comment by ValentaTomas** [comment]
Can you `git pull` on master and try starting the project with the [new instructions](https://github.com/e2b-dev/e2b#get-started)? 
We added a way to start the app via Docker to solve a lot of dependency and connection issues people had.

You essentially just need to do the two steps:

## 1. Add env var
Create .env file by copying the [.env.example](https://github.com/e2b-dev/e2b/blob/master/.env.example)
```
cp .env.example .env
```
and fill in the following variable:
- OPENAI_API_KEY - your [OpenAI key](https://platform.openai.com/account/api-keys)

## 2. Start the app
```
npm start
```
Then open the page on http://localhost:3000/.

**Comment by lucasgonze** [comment]
Looks good to me.
