### ISSUE TITLE
Using `e2b build` in Windows miniconda terminal fails

### ISSUE THREAD

**Issue by ValentaTomas** [e2b-dev/E2B#250]
When you use `e2b build` on Windows with miniconda terminal there seems to be a bug when creating the TAR archive because during the building of the template on our infra the builder cannot find the required files probably because of invalid paths in the archive.

`e2b.Dockerfile`
```Dockerfile
# You can use most Debian-based base images
FROM ubuntu:22.04

# Install dependencies and customize sandbox
RUN apt update \
    && apt install sudo
```

```
(e2b) PS F:\my\e2b> e2b build --name "yyy"

Preparing sandbox template building (1 files in Docker build context).
Found ./e2b.Dockerfile that will be used to build the sandbox template.
Started building the sandbox template xxx yyy

API error (500): Cannot locate specified Dockerfile: Dockerfile
Build failed, received error while building docker image.
Error:
❌ Building sandbox template xxx yyy failed.
Check the logs above for more details or contact us (https://e2b.dev/docs/getting-help) to get help.

    at qX (C:\Users\User\AppData\Roaming\npm\node_modules\@e2b\cli\dist\index.js:148:84)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\@e2b\cli\dist\index.js:123:1510
```

We should check the CLI logic for creating the archive and resolving path so it work for Windows paths too.
When using WSL the CLI works normally.

<sub>[E2B-436](https://linear.app/e2b/issue/E2B-436/using-e2b-build-on-windows-miniconda-terminal-fails)</sub>

**Comment by vaibhavard** [comment]
Rename e2b.Dockerfile to Dockerfile and it works

**Comment by ValentaTomas** [comment]
@vaibhavard Thanks for the feedback. You too are using Windows, right?
We encountered a similar error that happens when you put `e2b.Dockerfile` into `.dockerignore` so I'm just checking if your bug was not something else internally.

**Comment by ValentaTomas** [comment]
This might be solved because we are using local Docker now.

**Comment by ValentaTomas** [comment]
Closing as this should be fixed with local docker.
