### ISSUE TITLE
E2B CLI is not working when using Node.js 20.4.x - 20.5.x

### ISSUE THREAD

**Issue by ValentaTomas** [e2b-dev/E2B#251]
When you are using Node.js 20.4.x - 20.5.x the E2B CLI is crashing when a fetch command is 

```
$ e2b build

Preparing sandbox template building (4 files in Docker build context). 
Found ./e2b.Dockerfile that will be used to build the sandbox template.
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async WX (/Users/xxx/.nvm/versions/node/v20.5.1/lib/node_modules/@e2b/cli/dist/index.js:149:775)
    at async e.<anonymous> (/Users/xxx/.nvm/versions/node/v20.5.1/lib/node_modules/@e2b/cli/dist/index.js:123:1425) {
  cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -54,
    code: 'ECONNRESET',
    syscall: 'read'
  }
```

The CLI works when using other Node.js versions.

<sub>[E2B-437](https://linear.app/e2b/issue/E2B-437/e2b-cli-is-not-working-when-using-nodejs-204x-205x)</sub>

**Comment by ValentaTomas** [comment]
Closed as stale—we recommend updating the installed Node version.
