### ISSUE TITLE
error after yarn dev

### ISSUE THREAD

**Issue by BangerTech** [e2b-dev/e2b#3]
Hey guys,

first of all thank you for the work. 
I´ve tried it out but i´m getting some errors after starting everything with yarn dev: 
When i´m trying to login i´ll get the message: Failed to fetch

```
yarn run v1.22.19
$ npx concurrently -p none "next dev" "yarn start:api" "yarn start:playground"
$ cd api-service && QUART_APP=app:app PYTHONUNBUFFERED=1 poetry run quart --debug run --reload --port 49155
$ cd api-service/playground && yarn dev
$ concurrently "nodemon -q" "nodemon --config nodemon-tsoa.json "
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/debian-dev/e2b/e2b/.env
warn  - You have enabled experimental feature (swcPlugins) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

[1] [nodemon] 2.0.21
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching path(s): src/**/*Controller.ts
[1] [nodemon] watching extensions: ts
[1] [nodemon] starting `tsoa spec-and-routes`
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/codegen-gAr6YSV0-py3.9/bin/quart", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/codegen-gAr6YSV0-py3.9/lib/python3.9/site-packages/quart/cli.py", line 771, in main
    cli.main()
  File "/root/.cache/pypoetry/virtualenvs/codegen-gAr6YSV0-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/codegen-gAr6YSV0-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/codegen-gAr6YSV0-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/codegen-gAr6YSV0-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/codegen-gAr6YSV0-py3.9/lib/python3.9/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/codegen-gAr6YSV0-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/codegen-gAr6YSV0-py3.9/lib/python3.9/site-packages/quart/cli.py", line 656, in run_command
    app = info.load_app()
  File "/root/.cache/pypoetry/virtualenvs/codegen-gAr6YSV0-py3.9/lib/python3.9/site-packages/quart/cli.py", line 245, in load_app
    app = locate_app(import_name, name)
  File "/root/.cache/pypoetry/virtualenvs/codegen-gAr6YSV0-py3.9/lib/python3.9/site-packages/quart/cli.py", line 175, in locate_app
    module = import_module(module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/debian-dev/e2b/e2b/api-service/app.py", line 11, in <module>
    from codegen import Codegen
  File "/home/debian-dev/e2b/e2b/api-service/codegen/__init__.py", line 1, in <module>
    from .codegen import Codegen
  File "/home/debian-dev/e2b/e2b/api-service/codegen/codegen.py", line 19, in <module>
    from session.env import EnvVar
  File "/home/debian-dev/e2b/e2b/api-service/session/__init__.py", line 1, in <module>
    from .playground.nodejs import NodeJSPlayground
  File "/home/debian-dev/e2b/e2b/api-service/session/playground/__init__.py", line 1, in <module>
    from .base import Playground
  File "/home/debian-dev/e2b/e2b/api-service/session/playground/base.py", line 18, in <module>
    class Playground(Session):
  File "/home/debian-dev/e2b/e2b/api-service/session/playground/base.py", line 47, in Playground
    timeout: float | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn start:api exited with code 1
[0] Listening at http://localhost:49160
event - compiled client and server successfully in 5.1s (1189 modules)
[1] [nodemon] clean exit - waiting for changes before restart
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 993 ms (1190 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling /sign (client and server)...
event - compiled client and server successfully in 1443 ms (1199 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
[0] Listening at http://localhost:49160
wait  - compiling /[projectID] (client and server)...
event - compiled client and server successfully in 2.4s (1765 modules)
```

**Comment by ValentaTomas** [comment]
Hi, thanks for opening an issue!

There seems to be an error when starting Python API - can you please check your Python version? I think you are not running python 3.10 and the error is described here https://github.com/tiangolo/typer/issues/371.

Also, if you are getting `failed to fetch` error during the login, there may be some problem with the local Supabase - was that started without problems?

**Comment by BangerTech** [comment]
thanks for your answer. 
so my python version is Python 3.11.1
the Supabase startet without problems. 
i´ve just updated python and restarted the Supabase but still the same error. Maybe reinstall everything?

**Comment by BangerTech** [comment]
one step further ;-) 
soo it was the root/.cache folder i had to delete the files in there. 
now i still get one error and still not able to login with admin@admin.com
<img width="2060" alt="Screenshot 2023-04-03 at 20 12 07" src="https://user-images.githubusercontent.com/73241309/229592649-8f65fd3a-20c5-49ff-bcfd-7fd6645bf6b5.png">

**Comment by ValentaTomas** [comment]
I think that now you are missing the deleted deps :D (quart)

Somehow the Python virtualenv is creating env with Python 3.9
![Screenshot 2023-04-03 at 20 19 49](https://user-images.githubusercontent.com/49156497/229593816-f93b9cbf-f9ca-4b79-a078-efd2cee9a125.png)

I tried it locally and the following steps should fix it:

1. Go to `api-service/` and run `poetry env use python3.10` command
2. Go to the top level directory and run `yarn install:api-service`
3. Try `yarn dev` again.

**Comment by BangerTech** [comment]
if i go to api-service and type poetry env use python3.11.1 (my installed version)  i´ll get No such file or directory 
same with 3.10 of course ;-) 
if i proceed with yarn install:api-service it installs everything based on my old python and i´ll get the same error as on post one. so i have to delete the root/.cache folder again and type yarn dev. 
but the one quart error pops up again

**Comment by ValentaTomas** [comment]
You should be able to switch the poetry python env with the command specifying the full path to your Python:

`poetry env use /full/path/to/python` (`poetry env use $(which python)` could work if your python is accessible as `python` from terminal.)

**Comment by BangerTech** [comment]
yap perfect thank you. The only part i´m missing right now is the chatgpt input field like you´ve posted a few days ago...

**Comment by ValentaTomas** [comment]
Do you mean the input field for generating UIs?

**Comment by ValentaTomas** [comment]
No, this is actually our fault. The UI generation is not finished and accessible right now - but we will be adding it here soon :D

You can join the Discord (https://discord.gg/U7KEcGErtQ) - we will be announcing the release there too.

**Comment by BangerTech** [comment]
ok thanks! 👌
