### ISSUE TITLE
ImportError: cannot import name 'EnvVars' from 'e2b'

### ISSUE THREAD

**Issue by shadk9** [e2b-dev/E2B#456]
**Describe the bug**
ImportError: cannot import name 'EnvVars' from 'e2b' (C:\Users\...\.venv\Lib\site-packages\e2b\__init__.py)

**To Reproduce**
install e2b and e2b_code_interpreter, and use code interpreter as normal.
I belive this to be related to some recent update, as I simply migrated one my code from one project to another, and installed e2b fresh, using poetry. The same code is running as normal in my "old" project, and this import error is not present.

**Expected behavior**
To not encounter this ImportError:

**Browser console output**
Console logs from your browser's developer tool console.

**Terminal commands & output**
Traceback (most recent call last):
  File "C:\Users\main.py", line 5, in <module>
    from cb import Chatbot
  File "C:\Users\cb.py", line 10, in <module>
    from e2b_repl import PythonAstREPLTool_e2b
  File "C:\Users\e2b_repl.py", line 20, in <module>
    from e2b_code_interpreter import CodeInterpreter
  File "C:\Users\.venv\Lib\site-packages\e2b_code_interpreter\__init__.py", line 3, in <module>
    from .main import CodeInterpreter, JupyterExtension
  File "C:\Users\.venv\Lib\site-packages\e2b_code_interpreter\main.py", line 12, in <module>
    from e2b import EnvVars, ProcessMessage, Sandbox
ImportError: cannot import name 'EnvVars' from 'e2b'

**Desktop (please complete the following information):**

- OS: Windows 11

**Comment by shadk9** [comment]
So, I believe the issue is from version 0.17.2a60 and that version 0.17.1 works fine.

**Comment by ValentaTomas** [comment]
Hey @shadk9, the 0.17.2a60 was an older Beta version.

We actually released the Beta as 1.0.1 (https://pypi.org/project/e2b-code-interpreter/1.0.1/).
The `EnvVars` type is no longer exported because the env vars can now be just the standard `Dict[str, str]` type.

**Comment by ValentaTomas** [comment]
@shadk9 Were you able to resolve this in the end?

**Comment by ValentaTomas** [comment]
The type is no longer exported, closing issue.
