### ISSUE TITLE
Crashed when I tried to run

### ISSUE THREAD

**Issue by luisrock** [e2b-dev/e2b#6]
![localhost-3000-laravel-test](https://user-images.githubusercontent.com/3841676/230158909-e7dee7fb-bce9-43a8-aa53-068a5005f4bd.png)

**Comment by ValentaTomas** [comment]
Hi, can you paste here the output from the `yarn dev` command?

**Comment by luisrock** [comment]
```
[1] [nodemon] clean exit - waiting for changes before restart
event - compiled client and server successfully in 2.1s (1187 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 326 ms (1225 modules)
[0] node:events:490
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0]
[0] Error: listen EADDRINUSE: address already in use :::49160
[0]     at Server.setupListenHandle [as _listen2] (node:net:1740:16)
[0]     at listenInCluster (node:net:1788:12)
[0]     at Server.listen (node:net:1876:7)
[0]     at Function.listen (/Users/maurolopes/nodeSites/e2b/api-service/playground/node_modules/express/lib/application.js:635:24)
[0]     at Object.<anonymous> (/Users/maurolopes/nodeSites/e2b/api-service/playground/lib/server.js:4:16581)
[0]     at Module._compile (node:internal/modules/cjs/loader:1275:14)
[0]     at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
[0]     at Module.load (node:internal/modules/cjs/loader:1133:32)
[0]     at Module._load (node:internal/modules/cjs/loader:972:12)
[0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (node:net:1767:8)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -48,
[0]   syscall: 'listen',
[0]   address: '::',
[0]   port: 49160
[0] }
[0]
[0] Node.js v19.7.0
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 203 ms (1226 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
wait  - compiling /[projectID] (client and server)...
event - compiled client and server successfully in 1010 ms (1769 modules)
warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org/docs/messages/fast-refresh-reload
[2023-04-05 14:44:25 -0300] [79822] [INFO] 127.0.0.1:64209 OPTIONS /generate 1.1 200 0 7824
'+++ Blocks:'
[{'content': '', 'id': 'thZ_X0Ufht53moDIaiO4j', 'type': 'RequestBody'},
 {'content': '', 'id': 'yhjF34Z1DHLtSooYv8crA', 'type': 'Description'},
 {'content': '', 'id': 'BoCtbUWTeFyhMAjmDD5Dn', 'type': 'Instructions'}]
'--- Blocks:'
[2023-04-05 14:44:26,010] ERROR in app: Exception on request POST /generate
Traceback (most recent call last):
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x123424490>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/quart/app.py", line 1650, in handle_request
    return await self.full_dispatch_request(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/quart/app.py", line 1675, in full_dispatch_request
    result = await self.handle_user_exception(error)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/quart/app.py", line 1107, in handle_user_exception
    raise error
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/quart/app.py", line 1673, in full_dispatch_request
    result = await self.dispatch_request(request_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/quart/app.py", line 1718, in dispatch_request
    return await self.ensure_async(handler)(**request_.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/nodeSites/e2b/api-service/app.py", line 66, in generate
    playground_tools, playground = create_playground_tools(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/nodeSites/e2b/api-service/codegen/tools/playground/main.py", line 13, in create_playground_tools
    playground = NodeJSPlayground(get_envs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/nodeSites/e2b/api-service/session/playground/nodejs.py", line 14, in __init__
    super().__init__(NodeJSPlayground.node_js_env_id, get_envs)
  File "/Users/maurolopes/nodeSites/e2b/api-service/session/playground/base.py", line 27, in __init__
    super().__init__(env_id, get_envs)
  File "/Users/maurolopes/nodeSites/e2b/api-service/session/session.py", line 26, in __init__
    result = self.api.create_sessions(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "/Users/maurolopes/nodeSites/e2b/api-service/playground_client/api/default_api.py", line 245, in create_sessions
    return self.create_sessions_with_http_info(create_sessions_request, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "/Users/maurolopes/nodeSites/e2b/api-service/playground_client/api/default_api.py", line 348, in create_sessions_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/nodeSites/e2b/api-service/playground_client/api_client.py", line 403, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/nodeSites/e2b/api-service/playground_client/api_client.py", line 212, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/Users/maurolopes/nodeSites/e2b/api-service/playground_client/api_client.py", line 447, in request
    return self.rest_client.post_request(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/nodeSites/e2b/api-service/playground_client/rest.py", line 270, in post_request
    return self.request("POST", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/nodeSites/e2b/api-service/playground_client/rest.py", line 156, in request
    r = self.pool_manager.request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=49160): Max retries exceeded with url: /sessions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x123424490>: Failed to establish a new connection: [Errno 61] Connection refused'))
Executing <Task cancelling name='Task-18' coro=<ASGIHTTPConnection.handle_request() running at /Users/maurolopes/Library/Caches/pypoetry/virtualenvs/codegen-TOdOB9Ip-py3.11/lib/python3.11/site-packages/quart/asgi.py:102> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py:427> cb=[_wait.<locals>._on_completion() at /usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py:509] created at /usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py:670> took 0.156 seconds
[2023-04-05 14:44:26 -0300] [79822] [INFO] 127.0.0.1:64209 POST /generate 1.1 500 411613 267427
```

**Comment by ValentaTomas** [comment]
The port `49160` that we are using for API seems to be blocked by something - can you shut it down, check if it is free and try again?

**Comment by luisrock** [comment]
Killing the process on that port did it. Can we select different ports on launching? Is it possible to the service to pick an available port if the default one is taken?

**Comment by ValentaTomas** [comment]
Yeah, we are working on solving the port issues. 👍
